// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdk_PObPJtU1XO75dQMJBUT52PYPw16nc',
    appId: '1:560929017132:web:e0263a76069008595cf089',
    messagingSenderId: '560929017132',
    projectId: 'finsmart-ai-9a3cd',
    authDomain: 'finsmart-ai-9a3cd.firebaseapp.com',
    storageBucket: 'finsmart-ai-9a3cd.firebasestorage.app',
    measurementId: 'G-9J2VQ4BHPV',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdk_PObPJtU1XO75dQMJBUT52PYPw16nc',
    appId: '1:560929017132:web:e0263a76069008595cf089',
    messagingSenderId: '560929017132',
    projectId: 'finsmart-ai-9a3cd',
    authDomain: 'finsmart-ai-9a3cd.firebaseapp.com',
    storageBucket: 'finsmart-ai-9a3cd.firebasestorage.app',
    measurementId: 'G-9J2VQ4BHPV',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-wjT8k0bUB1vvFDczVStgaIz50_TbZEs',
    appId: '1:560929017132:ios:ddd4b42e22d7dacd5cf089',
    messagingSenderId: '560929017132',
    projectId: 'finsmart-ai-9a3cd',
    storageBucket: 'finsmart-ai-9a3cd.firebasestorage.app',
    iosClientId: '560929017132-a0ia8rpv0qqgdpvp6uj58926m4uj7f4a.apps.googleusercontent.com',
    iosBundleId: 'com.finsmart.finsmartAi',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8iwi4xbJCiuFB8Q21rG2YV4WDIwKaZ2w',
    appId: '1:560929017132:android:597445d2f2b2d20f5cf089',
    messagingSenderId: '560929017132',
    projectId: 'finsmart-ai-9a3cd',
    storageBucket: 'finsmart-ai-9a3cd.firebasestorage.app',
  );
}
